### ISSUE TITLE
Dark theme: Non-highlighed search results are not readable

### ISSUE THREAD

**Issue by dclaganiere** [duke1102/pocketduelist.pw#1]
![image](https://user-images.githubusercontent.com/2326067/40404339-e2d7c750-5e1c-11e8-89a0-21b961ffcca9.png)

Note that in the screenshot, any options below Blue-eyes White Dragon are using white text on a white background.

Might just be that the search should have a dark theme.

**Comment by duke1102** [comment]
Hey. Thanks for the feedback. The dark theme was a rather quick and dirty drop-in after Winds suggested that a dark theme would be a nice addition. I'll do some tweaks soon to make the search results etc. fit into the theme.

**Comment by duke1102** [comment]
I just tweaked the dark theme a bit and it should now be easier to read. ;)
