### ISSUE TITLE
Duelists: Search does not work

### ISSUE THREAD

**Issue by dclaganiere** [duke1102/pocketduelist.pw#2]
![image](https://user-images.githubusercontent.com/2326067/40404421-5e2f112e-5e1d-11e8-869d-cde5d613e0c0.png)

The search displays the full list when supplying a search criteria.

**Comment by duke1102** [comment]
Hey. That's the intended way actually. It's programmed so that it always loads in the full 39 Duelist names. I'll make some small adjustments to make that more clear.

**Comment by dclaganiere** [comment]
If that's the case, the search part should be removed imo, as it does nothing (unless it's supposed to select the right person, but not filter)

**Comment by duke1102** [comment]
Removed the search option.
