### ISSUE TITLE
Switching duelists does not always switch decklists

### ISSUE THREAD

**Issue by dclaganiere** [duke1102/pocketduelist.pw#5]
Seems like if you re-select a duelist, their decklist is not loaded.

### Repro Steps
1. Select the "Duelists" tab.
2. Open the "Choose a Duelist!" dropdown and select "Jono".
3. Open the dropdown again and select "Teana".
4. Open the dropdown again and select "Jono".

Expected: Jono's decklist is shown.
Actual: Teana's decklist is shown.

**Comment by duke1102** [comment]
Hey, thanks for the issue.
GenericMadScientist told me about it yesterday and I confirmed it. I suspect it has to do with disabling the search function I put in the other day. I'll look into fixing it soon.

**Comment by duke1102** [comment]
Should be fixed now. :]
